import { z } from 'zod'

const EnvSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().int().positive().default(4000),
  TRUST_PROXY: z.coerce.boolean().default(false),
  CORS_ORIGINS: z.string().optional(),
  DATABASE_URL: z.string().min(1, 'DATABASE_URL is required'),
  REDIS_URL: z.string().url().optional(),
  OPENCLAW_GATEWAY_URL: z.string().url().optional(),
  OPENCLAW_GATEWAY_TOKEN: z.string().optional(),
  OPENCLAW_CONFIG_PATH: z.string().optional(),
  OPENCLAW_WHATSAPP_ACCOUNT: z.string().default('default'),
  OPENCLAW_WHATSAPP_DM_POLICY: z.enum(['pairing', 'allowlist', 'open', 'disabled']).default('allowlist'),
  OPENCLAW_AUTO_ALLOWLIST_REQUESTS: z.coerce.boolean().default(true),
  OPENCLAW_ALLOWLIST_SYNC_MODE: z.enum(['auto', 'api', 'config']).default('auto'),
  OPENCLAW_ALLOWLIST_SYNC_PATH: z.string().optional(),
  OPENCLAW_WHATSAPP_SEND_PATH: z.string().default('/api/channels/whatsapp/send'),
  BACKUP_DIR: z.string().optional(),
  BACKEND_LOG_DIR: z.string().optional(),
  REPORTS_DIR: z.string().optional(),
  POSTGRES_CONTAINER_NAME: z.string().default('nara-postgres-1'),
  REMINDER_WORKER_ENABLED: z.coerce.boolean().default(true),
  REMINDER_WORKER_INTERVAL_MS: z.coerce.number().int().positive().default(60_000),
  REPORT_WORKER_ENABLED: z.coerce.boolean().default(true),
  REPORT_WORKER_INTERVAL_MS: z.coerce.number().int().positive().default(300_000),
  RATE_LIMIT_ENABLED: z.coerce.boolean().default(true),
  RATE_LIMIT_WINDOW_MS: z.coerce.number().int().positive().default(60_000),
  RATE_LIMIT_MAX: z.coerce.number().int().positive().default(240),
  AUTH_RATE_LIMIT_MAX: z.coerce.number().int().positive().default(12),
  AGENT_RATE_LIMIT_MAX: z.coerce.number().int().positive().default(120),
  MUTATION_RATE_LIMIT_MAX: z.coerce.number().int().positive().default(80),
  JWT_SECRET: z.string().min(1, 'JWT_SECRET is required'),
  AGENT_API_SECRET: z.string().min(1, 'AGENT_API_SECRET is required'),
  OPERATOR_USERNAME: z.string().min(1, 'OPERATOR_USERNAME is required'),
  OPERATOR_PASSWORD: z.string().min(12, 'OPERATOR_PASSWORD must be at least 12 characters'),
})

export const env = EnvSchema.parse(process.env)
